import Commerce.Claims
#print axioms CommerceKernel.app_core_reference_exact
#print axioms CommerceKernel.app_core_reference_private
#print axioms CommerceKernel.app_flow_exact
#print axioms CommerceKernel.app_flow_readonly_denied
#print axioms CommerceKernel.app_read_exact
#print axioms CommerceKernel.app_read_safe
#print axioms CommerceKernel.app_tool_disabled
#print axioms CommerceKernel.app_tool_exact
#print axioms CommerceKernel.cancellation_exact
#print axioms CommerceKernel.cancellation_safe
#print axioms CommerceKernel.checkout_contact_exact
#print axioms CommerceKernel.checkout_review_exact
#print axioms CommerceKernel.completion_exact
#print axioms CommerceKernel.completion_safe
#print axioms CommerceKernel.customer_group_net_exact
#print axioms CommerceKernel.customer_group_unknown_denied
#print axioms CommerceKernel.destination_tax_exact
#print axioms CommerceKernel.discount_bounded
#print axioms CommerceKernel.discount_conservation
#print axioms CommerceKernel.discount_exact
#print axioms CommerceKernel.discount_requested
#print axioms CommerceKernel.download_blocked_denied
#print axioms CommerceKernel.download_exact
#print axioms CommerceKernel.download_payment_required
#print axioms CommerceKernel.financial_contact_required
#print axioms CommerceKernel.flow_delay_exact
#print axioms CommerceKernel.manual_payment_exact
#print axioms CommerceKernel.manual_payment_safe
#print axioms CommerceKernel.order_edit_exact
#print axioms CommerceKernel.platform_exact
#print axioms CommerceKernel.platform_personal_required
#print axioms CommerceKernel.receipt_exact
#print axioms CommerceKernel.receipt_exact_behavior
#print axioms CommerceKernel.refund_bounded
#print axioms CommerceKernel.refund_exact
#print axioms CommerceKernel.refund_zero_denied
#print axioms CommerceKernel.replay_exact
#print axioms CommerceKernel.replay_open_fingerprint
#print axioms CommerceKernel.replay_same_cart
#print axioms CommerceKernel.reservation_authorized_unvoided
#print axioms CommerceKernel.reservation_captured_denied
#print axioms CommerceKernel.reservation_release_exact
#print axioms CommerceKernel.revision_exact
#print axioms CommerceKernel.revision_exact_behavior
#print axioms CommerceKernel.rule_authenticated_exact
#print axioms CommerceKernel.rule_comparison_exact
#print axioms CommerceKernel.rule_guest_denied
#print axioms CommerceKernel.rule_xor_empty
#print axioms CommerceKernel.rule_xor_exact
#print axioms CommerceKernel.scope_authenticated_known
#print axioms CommerceKernel.scope_exact
#print axioms CommerceKernel.scope_explicit_no_escalation
#print axioms CommerceKernel.shop_archived_denied
#print axioms CommerceKernel.shop_availability_exact
#print axioms CommerceKernel.stock_conservation
#print axioms CommerceKernel.stock_exact
#print axioms CommerceKernel.stock_positive_bounded
#print axioms CommerceKernel.terminal_edit_denied
