/** Guest SDK regression: context/result provenance, action round trip and independent sizing. */
import assert from "node:assert/strict";
import { connectCommerce } from "../../extensions/sdk/browser.js";
let listener;
const sent = [], timers = new Map();
globalThis.parent = { postMessage: value => sent.push(value) };
globalThis.addEventListener = (_, fn) => { listener = fn; };
globalThis.setTimeout = fn => { const id = timers.size + 1; timers.set(id, fn); return id; };
globalThis.clearTimeout = id => timers.delete(id);
const waiting = connectCommerce();
listener({ source: {}, data: { type: "commerce.context", nonce: "foreign" } });
listener({ source: parent, data: { type: "commerce.context", app: "product_lab", locale: "de-DE", nonce: "owned", context: { productId: "mug" } } });
const sdk = await waiting;
assert.equal(sdk.locale, "de-DE");
assert.equal(sdk.context.productId, "mug");
assert.equal(sdk.token, undefined);
const answer = sdk.action("recommend", { productId: "mug", question: "Care?" });
const request = sent[0];
assert.equal(request.nonce, "owned");
listener({ source: parent, data: { type: "commerce.result", nonce: "foreign", id: request.id, result: "forged" } });
assert.equal(timers.size, 1);
listener({ source: {}, data: { type: "commerce.result", nonce: "owned", id: request.id, result: "forged" } });
assert.equal(timers.size, 1);
listener({ source: parent, data: { type: "commerce.result", nonce: "owned", id: request.id, result: { answer: "verified" } } });
assert.deepEqual(await answer, { answer: "verified" });
assert.equal(timers.size, 0);
sdk.resize(420);
assert.deepEqual(sent[1], { type: "commerce.resize", nonce: "owned", height: 420 });
let observed;
const unsubscribe = sdk.onContext(value => { observed = value.productId; });
listener({source:parent, data:{type:"commerce.context", app:"product_lab", locale:"de-DE", nonce:"owned", context:{productId:"chair"}}});
assert.equal(sdk.context.productId, "chair");
assert.equal(observed, "chair");
unsubscribe();
const error = sdk.action("missing");
const next = sent[2];
listener({ source: parent, data: { type: "commerce.result", nonce: "owned", id: next.id, error: "Rejected" } });
await assert.rejects(error, /Rejected/);
console.log("PASS guest SDK: scoped context, source/nonce checks, action result/error and resize; no host credential");
