//! Append-only ordered migration source catalogue; deployed checksums are never rewritten.
pub(super) const SCHEMA: &[(&str, &str)] = &[
    // New migrations stay append-only below.
    // International translation jobs are additive and independent of earlier domain schemas.
    // Product/category management is append-only; earlier migration hashes stay intact.
    // Append-only entries are applied in dependency order below.
    ("001", include_str!("../../migrations/001.sql")),
    (
        "002-managed",
        include_str!("../../migrations/002-managed.sql"),
    ),
    (
        "004-context",
        include_str!("../../migrations/004-context.sql"),
    ),
    (
        "006-commerce",
        include_str!("../../migrations/006-commerce.sql"),
    ),
    (
        "008-workspaces",
        include_str!("../../migrations/008-workspaces.sql"),
    ),
    (
        "010-apps-intelligence-payments",
        include_str!("../../migrations/010-apps-intelligence-payments.sql"),
    ),
    (
        "011-documents-managed",
        include_str!("../../migrations/011-documents-managed.sql"),
    ),
    (
        "012-checkout-handoff",
        include_str!("../../migrations/012-checkout-handoff.sql"),
    ),
    (
        "014-bounded-catalog",
        include_str!("../../migrations/014-bounded-catalog.sql"),
    ),
    (
        "013-staging-developer",
        include_str!("../../migrations/013-staging-developer.sql"),
    ),
    (
        "014-customer-accounts",
        include_str!("../../migrations/014-customer-accounts.sql"),
    ),
    (
        "015-rules-flows-channels",
        include_str!("../../migrations/015-rules-flows-channels.sql"),
    ),
    (
        "016-merchant-operations",
        include_str!("../../migrations/016-merchant-operations.sql"),
    ),
    (
        "017-integration-access",
        include_str!("../../migrations/017-integration-access.sql"),
    ),
    (
        "018-order-state-machine",
        include_str!("../../migrations/018-order-state-machine.sql"),
    ),
    (
        "019-workflow-schema",
        include_str!("../../migrations/019-workflow-schema.sql"),
    ),
    (
        "020-customer-addresses",
        include_str!("../../migrations/020-customer-addresses.sql"),
    ),
    (
        "021-demo-addresses",
        include_str!("../../migrations/021-demo-addresses.sql"),
    ),
    (
        "022-app-evidence",
        include_str!("../../migrations/022-app-evidence.sql"),
    ),
    (
        "023-app-poll-scheduling",
        include_str!("../../migrations/023-app-poll-scheduling.sql"),
    ),
    (
        "024-platform",
        include_str!("../../migrations/024-platform.sql"),
    ),
    (
        "025-automation-pipelines",
        include_str!("../../migrations/025-automation-pipelines.sql"),
    ),
    (
        "026-product-catalog",
        include_str!("../../migrations/026-product-catalog.sql"),
    ),
    (
        "027-product-search",
        include_str!("../../migrations/027-product-search.sql"),
    ),
    (
        "028-translations",
        include_str!("../../migrations/028-translations.sql"),
    ),
    (
        "029-developer-trash",
        include_str!("../../migrations/029-developer-trash.sql"),
    ),
    (
        "030-company-settings",
        include_str!("../../migrations/030-company-settings.sql"),
    ),
    (
        "031-channel-commerce",
        include_str!("../../migrations/031-channel-commerce.sql"),
    ),
    (
        "032-image-jobs",
        include_str!("../../migrations/032-image-jobs.sql"),
    ),
    (
        "033-knowledge-workspace",
        include_str!("../../migrations/033-knowledge-workspace.sql"),
    ),
    (
        "033-managed-knowledge",
        include_str!("../../migrations/033-managed-knowledge.sql"),
    ),
    (
        "034-entity-history",
        include_str!("../../migrations/034-entity-history.sql"),
    ),
    (
        "035-history-finalization",
        include_str!("../../migrations/035-history-finalization.sql"),
    ),
    (
        "036-app-assistants",
        include_str!("../../migrations/036-app-assistants.sql"),
    ),
    (
        "037-read-context-cache",
        include_str!("../../migrations/037-read-context-cache.sql"),
    ),
    (
        "038-tenant-references",
        include_str!("../../migrations/038-tenant-references.sql"),
    ),
    (
        "039-explicit-payment-attribution",
        include_str!("../../migrations/039-explicit-payment-attribution.sql"),
    ),
    (
        "040-automation-defaults",
        include_str!("../../migrations/040-automation-defaults.sql"),
    ),
    (
        "041-platform-control",
        include_str!("../../migrations/041-platform-control.sql"),
    ),
    (
        "042-identity-frontends",
        include_str!("../../migrations/042-identity-frontends.sql"),
    ),
    (
        "043-payment-providers",
        include_str!("../../migrations/043-payment-providers.sql"),
    ),
    (
        "044-core-row-security",
        include_str!("../../migrations/044-core-row-security.sql"),
    ),
    (
        "045-resource-quotas",
        include_str!("../../migrations/045-resource-quotas.sql"),
    ),
    (
        "046-cache-invalidation",
        include_str!("../../migrations/046-cache-invalidation.sql"),
    ),
    (
        "047-order-reservations",
        include_str!("../../migrations/047-order-reservations.sql"),
    ),
    (
        "048-legal-privacy",
        include_str!("../../migrations/048-legal-privacy.sql"),
    ),
    (
        "049-rust-connectors",
        include_str!("../../migrations/049-rust-connectors.sql"),
    ),
    (
        "050-currency-price-jobs",
        include_str!("../../migrations/050-currency-price-jobs.sql"),
    ),
    (
        "051-multi-currency-ledger",
        include_str!("../../migrations/051-multi-currency-ledger.sql"),
    ),
    (
        "052-merchant-credentials",
        include_str!("../../migrations/052-merchant-credentials.sql"),
    ),
    (
        "053-channel-access",
        include_str!("../../migrations/053-channel-access.sql"),
    ),
    (
        "054-guest-customer-directory",
        include_str!("../../migrations/054-guest-customer-directory.sql"),
    ),
    (
        "055-hosted-apps",
        include_str!("../../migrations/055-hosted-apps.sql"),
    ),
    (
        "056-http-response-diagnostics",
        include_str!("../../migrations/056-http-response-diagnostics.sql"),
    ),
    (
        "057-core-hardening",
        include_str!("../../migrations/057-core-hardening.sql"),
    ),
];
