#!/usr/bin/env python3
"""Generate/check exact production and verification module inventory; listings are not coverage."""
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
TARGET = ROOT / 'docs/module-inventory.md'
GROUPS = {
    'Rust commerce and transport': ('src', {'.rs'}),
    'Studio, storefront, platform and shared frontend': ('frontend/src', {'.ts', '.tsx', '.css'}),
    'Independent apps, services and SDK': ('extensions', {'.py', '.js', '.wat', '.html'}),
    'Verification tools and fixtures': ('scripts', {'.py'}),
}


def responsibility(path):
    text = path.read_text()
    comment = re.search(r'(?m)^//! (.*)', text)
    if comment:
        return comment[1]
    comment = re.search(r'/\*\*?\s*([^\n]*?)(?:\*/|\n)', text)
    if comment:
        return comment[1].strip(' *')
    comment = re.search(r'"""([^\n"]+)', text)
    if comment:
        return comment[1]
    comment = re.search(r'(?m)^;;\s*(.+)', text)
    if comment:
        return comment[1]
    title = re.search(r'<title>(.*?)</title>', text, re.S | re.I)
    if title:
        return 'Isolated app interface: ' + title[1].strip()
    return 'Independent app entry; see extensions/README.md for its public contract.'


def render():
    lines = ['# Complete source inventory', '',
             'Generated by `python3 scripts/testing/source_inventory.py --write`. CI checks exact contents.', '',
             'This lists every checked-in source module in these roots, including files with no recorded hits. '
             'A responsibility or suite listing does **not** mean 100% coverage. '
             'See [testing](testing.md) for measured coverage and unverified paths.', '']
    for title, (directory, suffixes) in GROUPS.items():
        lines += ['## ' + title, '', '| Module | Responsibility |', '|---|---|']
        for path in sorted((ROOT / directory).rglob('*')):
            if not path.is_file() or path.suffix not in suffixes or '__pycache__' in path.parts:
                continue
            relative = path.relative_to(ROOT).as_posix()
            summary = responsibility(path).replace('|', '\\|')
            lines.append(f'| [{relative}](../{relative}) | {summary} |')
        lines.append('')
    return '\n'.join(lines).rstrip() + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    output = render()
    if args.write:
        TARGET.write_text(output)
    elif not TARGET.exists() or TARGET.read_text() != output:
        raise SystemExit('Source inventory drift: run scripts/testing/source_inventory.py --write')
    else:
        print('PASS exact source inventory and responsibility map')
